version: '3.8'

services:
  logbase-db:
    image: postgres:15-alpine
    container_name: logbase_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgresql}
      POSTGRES_DB: ${DB_NAME:-logbase_db}
    ports:
      - "5432:5432"
    volumes:
      - logbase_pgdata:/var/lib/postgresql/data

volumes:
  logbase_pgdata: